export const ROUTES = {
    PROFILEPAGE: '/profile',
    LOGINPAGE: '/login',
    USEFULSERVICESPAGE: '/usefulservices',
    EVENTSPAGE: '/',
    EVENTDETAILSPAGE: '/events/:id',
    CERTIFICATESPAGE: '/certificates',
    ADMINMAINPAGE: '/admin',
    ADMINUSERSPAGE: '/admin/users',
    ADMINUSERDETAILSPAGE: '/admin/users/:id',
    ADMINUSEFULSERVICESPAGE: '/admin/usefulservices',
    ADMINEVENTSPAGE: '/admin/events',
    ADMINEVENTDETAILSPAGE: '/admin/events/:id',
    ADMINEVENTCREATE: '/admin/events/create',
};